name: GitHub Actions CI Pipeline
run-name: ${{ github.actor }} is running pipeline 🚀
on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cloning...
        uses: actions/checkout@v3
      - name: Installing node...
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ matrix.node }}
      - name: NPM Install
        run: npm ci
      - name: Build
        run: npm run build:prod
      - name: Lint
        run: | 
          npm run lint  
          npm run lint:scss
      - name: Unit Tests
        run: npm run test:unit
      - name: Screenshot Tests
        run: |
          npm run storybook:build
          npm run test:screenshot:ci
        

  