name: GitHub Actions CI Pipeline
run-name: ${{ github.actor }} is running pipeline 🚀

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  DEPLOY_PATH: '${{ github.ref_name }}.${{ github.sha }}'

jobs:
  lint_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.12.0]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Cloning...
        uses: actions/checkout@v3
      - name: Installing node...
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ matrix.node }}
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          key: npm-${{ hashFiles('package-lock.json') }}
          path: ~/.npm
      - name: NPM Install
        run: npm ci
      - name: Lint
        run: | 
          npm run lint  
          npm run lint:scss
          npm run lint:types
      - name: Unit Tests
        id: unit_test
        run: npm run test:unit
      - name: Screenshot Tests
        if: ${{ !cancelled() }}
        id: screenshot_test
        run: |
          npm run storybook:build
          npm run test:screenshot:ci
      - name: Generate Screenshot Tests Report
        if: ${{ failure() }}
        run: |
          npm run visual:report:json
          npm run visual:report:html
      - name: Configure Deploy Path
        if: ${{ failure() }}
        working-directory: reports
        run: |
          mkdir $DEPLOY_PATH
          mv -v tests $DEPLOY_PATH/
          mv -v ../.loki $DEPLOY_PATH/tests/
          mv -v index.html $DEPLOY_PATH/
      - name: Upload GH Pages Artifact
        if: ${{ failure() && (steps.screenshot_test.conclusion == 'failure' || steps.unit_test.conclusion == 'failure') }}
        uses: actions/upload-pages-artifact@v3
        with: 
          path: 'reports'
      # TODO: add e2e tests

  deploy_test_reports:
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    if: ${{ failure() }}
    needs: [lint_and_test]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}${{ env.DEPLOY_PATH }}

    steps:
      - name: Setup Github Pages
        uses: actions/configure-pages@v4
      - name: Deploy Reports
        id: deployment
        uses: actions/deploy-pages@v4
 
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18.12.0]

    runs-on: ${{ matrix.os }}
    needs: [lint_and_test]

    steps: 
      - name: Cloning...
        uses: actions/checkout@v3
      - name: Installing node...
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ matrix.node }}
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          key: npm-${{ hashFiles('package-lock.json') }}
          path: ~/.npm
      - name: NPM Install
        run: npm ci
      - name: Build 
        run: npm run build:prod
    
    
  
        

  
